package com.practice.bytecode;

/**
 * 38. Decompile a Class File
 * Compile this class and use javap to inspect the generated bytecode.
 */
public class DecompileDemo {
    public static void main(String[] args) {
        System.out.println("DecompileDemo running.");
        int value = add(2, 3);
        System.out.println("Example result: " + value);
    }

    public static int add(int x, int y) {
        return x + y;
    }
}
